### ISSUE TITLE
Integration TODO's

### ISSUE THREAD

**Issue by axieax** [cs9447-team2/money-trees#35]
- [x] Frontend integration [TODO](https://github.com/cs9447-team2/money-trees/blob/c3155990239928546a2bf0d321672e37b203459c/apps/deployment/src/main.ts#L34) @fionaochee 
- [x] Pipeline CodeArtifact job [TODO](https://github.com/cs9447-team2/money-trees/blob/c3155990239928546a2bf0d321672e37b203459c/apps/hooks/pipeline/src/main.ts#L44) @stevenp2 
- [x] Pipeline scanner integration [TOOD](https://github.com/cs9447-team2/money-trees/blob/c80e4b3389b765b618845478c4f9f3959143dbd1/apps/hooks/pipeline/src/main.ts#L72) @lachlan-waugh

**Comment by stevenp2** [comment]
done
